name: Changelog
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  publish-changelog:
    name: Publish Changelog
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Create Changelog
        id: create_changelog
        uses: mikepenz/release-changelog-builder-action@v3.2.0
        with:
          configuration: "config/changelog_configuration.json"

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Github Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          body: ${{steps.create_changelog.outputs.changelog}}
          draft: true
          prerelease: false

      - name: Stop Gradle
        run: ./gradlew --stop
